addons:
  apt:
    packages:
      - make
before_install:
  - go mod download
  - "echo -e \"machine github.com\\n  login $GITHUB_TOKEN\" > ~/.netrc"
  - git lfs pull
before_script:
  - go version
branches:
  only:
    - main
dist: xenial
git:
  lfs_skip_smudge: true
go:
  - '1.16'
jobs:
  fast_finish: true
language: go
os:
  - linux
script: make gotest
env:
  global:
    - GO111MODULE=on
    - GIN_MODE=release