language: go
go:
  - '1.16'
addons:
  apt:
    packages:
      - make
before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull
  - make goinstall
branches:
  only:
    - main
git:
  lfs_skip_smudge: true
script: make gotest
dist: xenial
os:
  - linux
jobs:
  fast_finish: true
